%include "structs.asm"

%include "seg000/segment.asm"
%include "seg001/segment.asm"
%include "seg002/segment.asm"
%include "seg003/segment.asm"
%include "seg004/segment.asm"
%include "seg005/segment.asm"
%include "seg006/segment.asm"
%include "seg007/segment.asm"
%include "seg008/segment.asm"
%include "seg009/segment.asm"
%include "seg010/segment.asm"
%include "dseg/segment.asm"
%include "seg012/segment.asm"
%include "seg013/segment.asm"
