name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: marijnvdwerf/borland

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Archive build folder
      uses: actions/upload-artifact@v2
      with:
        name: output-build
        path: build
