name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: marijnvdwerf/borland

    steps:
    - uses: actions/checkout@v2

    - run: pwd
    - run: dosemu -dumb -d .
      env:
        TERM: dumb

    - name: Build
      run: make
    - name: Link
      run: dosemu -dumb -K . -E "D:\BORLANDC\BIN\TLINK.EXE /m /s /c BUILD/MAIN.OBJ, BUILD/YOGHO.EXE, BUILD/YOGHO.MAP"
    - run: ls build
