name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: marijnvdwerf/borland

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y nasm

    - name: Build
      run: make
